# Generated by Django 5.0.6 on 2024-06-29 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('desc', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='new_images', verbose_name='изображение')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='счетчик просмотров')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'статья блога',
                'verbose_name_plural': 'статьи блога',
                'permissions': [('set_published', 'Can change is_published field')],
            },
        ),
    ]
